### ISSUE TITLE
HDF5 attribute format to overlay statistics on image

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/plateviewer#10]
@tischi has suggested to overlay scores given in the attributes `WellInformation` and `ImageInformation` with the images (And I think this is a very good idea).

I am not quite sure about the proper format though. Quoting from Tischi's message on our slack channel:

```
I think those should be just Strings, but could be something like nn = 476, ni=34, s1=0.6, s2=0.7, s3=0.72 where si could be different scores and nn and ni gives the number of non-infected and infected cells in the well or image.
```

As far as I understand this, the proposed idea is to have
```
WellInformation = "nn=476, ni=34, ...."
```
Is this correct, @tischi?

**Comment by tischi** [comment]
> Is this correct, @tischi?

Yes, this was the idea. Btw: I am getting the bi-directional interaction of a table and the images working, so that would alleviate the need for the Well and SiteInformation a little bit, but I still think it is nice to have as an easy "summary string".

**Comment by constantinpape** [comment]
> Btw: I am getting the bi-directional interaction of a table and the images working, so that would alleviate the need for the Well and SiteInformation a little bit, but I still think it is nice to have as an easy "summary string".

I agree, it's still nice to have Well and Image information, to overlay information with the image directly and to show information if a table is not available.

I will add it to the new example data.
