### ISSUE TITLE
Support multi-resolution h5 (n5)

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/plateviewer#12]
Similar to #4 it would be nice to support some multi-resolution pyramid format to zoom out smooth for large plates.
I am not quite sure what's the best way to assemble this though:
- add multi-resolution for the individual images or
- make large image out of all images and compute multi-res for this

**Comment by tischi** [comment]
I think adding multi-resolution for the individual images would be the first thing to try.
With data set names such as:

`DAPI/ResolutionLevel0/data`
`DAPI/ResolutionLevel1/data`

And one high level attribute that specifies how many layers there are and what the down-sampling factor is. 

If you make one test file I could play with it.

We could also follow [this file format](http://open.bitplane.com/Default.aspx?tabid=268), but I think it would be easier now to stick to what we have already.

**Comment by constantinpape** [comment]
> I think adding multi-resolution for the individual images would be the first thing to try.
> With data set names such as:
> 
> `DAPI/ResolutionLevel0/data`
> `DAPI/ResolutionLevel1/data`
> 
> And one high level attribute that specifies how many layers there are and what the down-sampling factor is.
> 
> If you make one test file I could play with it.

Sounds good, I will add some test data later or tomorrow.

Yeah, let's not go for the imaris format, it is very verbose...

**Comment by tischi** [comment]
Another advantage of doing it the proposed way would be that it would be very similar to having one multi-res tiff files for each site and channel. So, I could hopefully reuse my code for that data type.

**Comment by tischi** [comment]
I wonder whether we should have a different naming scheme:
`DAPI/image`
`DAPI/image_scale2x2`
`DAPI/image_scale4x4`
So that the same naming scheme would also work in case there are no downsampling layers. Then it would only be:
`DAPI/image`
Without any scaling added to the data set name. Maybe this would be easier to reuse in case one would not have multi-resolution?
`DAPI/image`

**Comment by tischi** [comment]
I think we implemented this for batchHdf5.
