### ISSUE TITLE
Border around the images of a well

### ISSUE THREAD

**Issue by muzamilmkhan** [embl-cba/plateviewer#2]
Is it possible to have border around the images belonging to a particular well please
thanks

**Comment by tischi** [comment]
This seems to be working now. 
Please reopen the issue in case you have problems with it.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/2157566/160858412-ecfe4cfd-4ba5-4cfe-80a4-bb21a3fd40c2.png">
