### ISSUE TITLE
Loading image table fails

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/plateviewer#31]
Loading a "generic" image table fails. I guess the problem is that some of the column names the plateViewer relies on are missing.
It would be good to be able any image table (as long as it has a column `site_name`) though to explore new data.

![telesto_bug](https://user-images.githubusercontent.com/4263537/86577626-d2b1bb80-bf7a-11ea-964e-e164fff2dc0e.png)

**Comment by constantinpape** [comment]
@tischi 
In order to reproduce this, you can open the following plate:
`/g/kreshuk/data/covid/telesto/data-processed/training_set_plateviewer`
and then add the following image table:
`/g/kreshuk/data/covid/telesto/data-processed/training_set_plateviewer/training_set_table.hdf5`

**Comment by tischi** [comment]
are you using 
1. `Plugins>Screening>PlateViewer Advanced...`, or
2. `Plugins>Screening>PlateViewer...` ?

**Comment by constantinpape** [comment]
The normal mode (2.)

**Comment by tischi** [comment]
ok, and could it be that I do not have read access?

```
Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5LowLevelIOException: Low-level I/O:Read failed 
```

**Comment by constantinpape** [comment]
> ok, and could it be that I do not have read access?

Weird, you should have read access.
Just to be sure, I ran `chmod -R g+rwx .` in the top level now.

Another explanation: The image files in `training_set_plateviewer` are actual soft-links to `traning_set` 
I did this in order to map from the initial, arbitrary, names to a naming scheme that fits the plateViewer.
If you start from mac these will probably not work.

**Comment by constantinpape** [comment]
I could change to relative instead of absolute links, then it should work on mac as well.

**Comment by tischi** [comment]
Still same issue, maybe soft-links do not work, indeed.

**Comment by constantinpape** [comment]
> Still same issue, maybe soft-links do not work, indeed.

Ok, yes then I think the problem is the soft links; I think I use absolute paths in there, which would not work on mac.
I will replace with relative paths and let you know once it's done.

**Comment by constantinpape** [comment]
@tischi 
I updated the folder to use relative links.
This should work under mac now as well.

**Comment by tischi** [comment]
@constantinpape 
I started looking into it. What do you mean by "add a table"? 

For me, it does not find a table matching the naming scheme, which would need to be in this case: `training_set_plateviewer_table.hdf5`
And then it simply does not load anything. 

Do you maybe have a version where, if it does not find anything automatically, asks the user to browse to a table? 
I remember this may have been the case in some versions, but in my latest it is not...
If you think it is useful I could add it back.

**Comment by constantinpape** [comment]
> For me, it does not find a table matching the naming scheme, which would need to be in this case: `training_set_plateviewer_table.hdf5`
> And then it simply does not load anything.

Yes, the table name was incorrect and I fixed it.

> Do you maybe have a version where, if it does not find anything automatically, asks the user to browse to a table?

Yes, it seems like I still have this version, this is what happens in my plateViewer version with the incorrect table name:
![Screenshot from 2020-07-10 17-14-33](https://user-images.githubusercontent.com/4263537/87170409-9612f680-c2d1-11ea-9020-1f3e70969ba7.png)

With the correct table name it loads the table immediately and also crashes with the behaviour described above.

Maybe my plateVIewer version is not up-to-date?
But I have just updated fiji; I have plateViewer 0.4.2.
Maybe you didn't push the latest version to the update site?
Or am I using an outdated update site for plateViewer (I am still using EMBL-CBA)?

> I remember this may have been the case in some versions, but in my latest it is not...
> If you think it is useful I could add it back.

Yeah, I find this quite useful, but let's first figure out why the loading behaviour is different between your and my version.

**Comment by tischi** [comment]
If there is nothing pressing right now from your side, I would in fact first make a PlateViewer update site and then we take it from there. Ok?

**Comment by constantinpape** [comment]
> If there is nothing pressing right now from your side, I would in fact first make a PlateViewer update site and then we take it from there. Ok?

Yes, sounds good.

**Comment by tischi** [comment]
Working on this with this Test method:

`TestALMFSchemeWithCellProfilerTable`

**Comment by tischi** [comment]
- [ ] Add @larual data as test to repository
- [ ] Test using the command and post screenshot here and ping @larual by mail
- [ ] Update Fiji Update Site

**Comment by tischi** [comment]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/2157566/165265514-d0ba39c3-4c10-454a-8ba4-191e4e6e4343.png">


<img width="1504" alt="image" src="https://user-images.githubusercontent.com/2157566/165265145-10c204b6-67e7-4af4-853a-5b9175ebc211.png">

**Comment by larual** [comment]
Thanks @tischi! 
I will try it right away :)

**Comment by tischi** [comment]
I just now uploaded the new version to the update site; you may have to restart Fiji.

And did you already know the scatter plot?
- If you right click you can select the table columns.
- If you left click it will move to the respective images.

**Comment by larual** [comment]
I am updating Fiji at the moment.

I did know the scatter plot, but hadn't use it much. I'm sure I will now!
