### ISSUE TITLE
Plate Viewer File Formats for ImageExpress Micro

### ISSUE THREAD

**Issue by DuncanTN** [embl-cba/plateviewer#38]
Hi i am interested in using PlateViewer and I got an error error when trying to open my tif images:

My current filename structure is IM-Assays-EXP_"well name"" site number""channel number"
I am acquiring my images using ImageExpress Micro from Molecular Devices

**Comment by DuncanTN** [comment]
Thanks Christian. The changes you made now work. This is an excellent plugin.
Looking forward to future updates.

**Comment by tischi** [comment]
@DuncanTN 
You are welcome! If you don't mind, I am curious about who is using the plugin.
To get in touch you could send me a private message on https://forum.image.sc/
My handle there is @Christian_Tischer. 
But, of course, feel free to ignore this.
