### ISSUE TITLE
Operetta Harmony: field order may be wrong

### ISSUE THREAD

**Issue by tischi** [embl-cba/plateviewer#41]

**Comment by tischi** [comment]
This is how it currently looks (seems messed up):

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2157566/219863847-8f49e235-0e95-4942-96a2-9e804514dc5b.png">

**Comment by tischi** [comment]
Now it is looking like this, which is an improvement:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/2157566/219976224-26c54ec2-455d-450e-881c-2b723710ca68.png">

It is successfully distributing 11 fields to each well; but I don't know whether this is the correct arrangement within the well.

**Comment by ThomasMicroscopy** [comment]
Hello Tischi,
thank you for doing this. Indeed the order is a bit unorthodox. It starts in the middle and then zig-zags from the top. In this instance also 4 corners were not recorded (blank).
![WelllabelledR01-C01](https://user-images.githubusercontent.com/126269188/221219412-75f73888-da8e-480c-9697-15776c6bf0d7.jpg)

**Comment by tischi** [comment]
@ThomasMicroscopy 
This is indeed a very funny way to do this :-)
Is there an official documentation from the company about this?

**Comment by tischi** [comment]
And/or do you have more examples for this for other numbers of fields than 11?

**Comment by tischi** [comment]
I just read your mail, could it be that this means that there is no automatic way of assigning this?
In other words, if there are 11 fields, they could be distributed in different ways?
Then I think I would need to add something to the user interface that would allow to specify this mapping.
