### ISSUE TITLE
Operetta Harmony: Orientation Matrix

### ISSUE THREAD

**Issue by tischi** [embl-cba/plateviewer#43]
I found this in the XML; `<OrientationMatrix>[[1,0,0],[0,-1,0],[0,0,1]]</OrientationMatrix>`

Should we flip the image along the x-axis?

**Comment by ThomasMicroscopy** [comment]
No, not for the sample I sent you (other thread).  I find this "OrientationMatrix" only under the Channel information, after camera type, exception, emission, objectivemag, objectiveNA, exposure time. Here is another example, albeit from a higher version of Harmony):
 <OrientationMatrix>[[1.014058,0.002600,0,-120.8],[0.002530,-1.014014,0,61.4],[0,0,1.33,-6.811]]</OrientationMatrix> 
The values are the same for the three channels (red, green, dapi). Don't seem to change with well/field position.
The floating values would be difficult to reconcile with image orientation. So, not sure what this is.

**Comment by tischi** [comment]
Thanks @ThomasMicroscopy!
Could you ask the company what the `OrientationMatrix` means?
