### ISSUE TITLE
Issue loading files

### ISSUE THREAD

**Issue by myrne95** [embl-cba/plateviewer#45]
Hi!

I'm quite new to Fiji and I have tried using the Plateviewer plugin since it seemed like the perfect tool for my image analysis. I have a set of .tif images from a high-throughput microscope (96-well plate with 72 wells used, 4 tiles per well, 3 channels, 5 z-slices), and I would like to stitch all the images together in the correct order to reconstruct the plate (either using a maximum intensity projection, or the z slice with the best signal) for all channels separately. However, I already ran into an issue trying to load my files: 

![image](https://github.com/embl-cba/plateviewer/assets/138213153/5262f570-eaeb-4dc1-85d2-c554187a97eb)
![image](https://github.com/embl-cba/plateviewer/assets/138213153/78ce19ca-15f4-4fba-b04d-6102de7cf9d5)

What am I doing wrong here? 

Thanks in advance!

**Comment by tischi** [comment]
Hi,

Please check out the [currently supported file naming schemes](https://github.com/embl-cba/plateviewer#supported-file-naming-schemes). 

If yours is not among them we would need to add it. For this I would need some minimal test data, shared via some web file exchange system.

**Comment by myrne95** [comment]
Hi,

Thank you for the reply.

My scheme is not among the supported schemes, so I would appreciate it if you could add mine :)

Here is a link to the files:
https://gunet-my.sharepoint.com/:f:/g/personal/myra_nett_gu_se/EvPefsaO9LJJorls9fvhNLYBTgm7FiPB3WlMYdYbO6Pn3A?e=NWvdYU

A-H: row number, 
01-09: column number, 
fld = tile number (4 tiles per well), 
z= z slice (I only want to use z 3, so the middle slice)

Thank you for your help.

**Comment by tischi** [comment]
Thank you for sharing the data. I will try to do this next week.
Please feel free to ping me here again if you do not hear back from me.

**Comment by tischi** [comment]
@myrne95 

1. Could you please let me know which type of microscope is producing this data? 
2. I started downloading but those were too many files.... could you please upload only a subset of just two wells?

**Comment by myrne95** [comment]
1. IN Cell analyzer 6000
2. Sorry! Here you go: https://gunet-my.sharepoint.com/:f:/g/personal/myra_nett_gu_se/EhKqABQw8VlDm7rDXHcK2oABzxori2jA5eXx4TO31dH3Sg?e=sMRlyZ

**Comment by tischi** [comment]
OK, and in case of multi-channel data is there also something in the file name that encodes the channel?

**Comment by tischi** [comment]
@myrne95 

Let me also repeat my question from above such that we do not get confused :-)

1. in case of multi-channel data is there also something in the file name that encodes the channel?
1. will you take care that only one of the z-planes is present in the folder that you open? I do not have any logic for only opening a subset of z-planes; adding this would be too much work; although I could maybe add a regular expression option to only load certain files in general, in your case:  `.*z 3.*`...
1. otherwise if your data has indeed multiple z-planes, could you provide me with example data?


Then is seems for the data that you sent me I managed so far, does that look correct?

<img width="569" alt="image" src="https://github.com/embl-cba/plateviewer/assets/2157566/d2bdef00-357e-47a2-967b-4c29ae4116a2">

**Comment by tischi** [comment]
For my own reference, working on this here: https://github.com/mobie/mobie-viewer-fiji/pull/1050

**Comment by myrne95** [comment]
1. in case of multi-channel data is there also something in the file name that encodes the channel?
   Yes, I took the images in 3 channels: DAPI (UV - DAPI), green channel (Blue - FITC), and the red channel (Green - dsRed). 

Since my green staining did not work, I decided to skip it for now, but I am planning to repeat the experiment so it would be good if I could use it next time.  
   
2.  will you take care that only one of the z-planes is present in the folder that you open? 
I manually pre-selected my images and only added z = 3 to the folder, since otherwise it would become too complicated with the amount of images to process. I think only using one plane would be the best way to go, and whether I pre-select them myself or the macro doing it for me, does not matter so much but it might save me some time to have the regular expression option added if possible 

3. otherwise if your data has indeed multiple z-planes, could you provide me with example data? 
    I uploaded the rest of the well A1+A2 images with all channels and z-planes to the folder I shared with you :)

And yes, the images look correct.

Thank you!

**Comment by tischi** [comment]
Thank you @myrne95 !

Regarding the channels:

`A - 01(fld 1 wv Green - dsRed z 3).tif`

What part of this file name denotes the channel? 

Could you please post here a file name from the same plate with a different channel?

**Comment by myrne95** [comment]
Green - dsRed denotes the channel.

These are the same well, field, and plane in the other channels:
A - 01(fld 1 wv UV - DAPI z 3)
A - 01(fld 1 wv Blue - FITC) (I am not sure why Blue - FITC is not taken in all planes, something might have gone wrong during acquisition there..)

**Comment by tischi** [comment]
oh, the `z` letter _only_ appears if there are multiple z planes?! that makes it harder to parse....

**Comment by myrne95** [comment]
Yes, but in reality every channel should be taken in the same number of z planes

**Comment by tischi** [comment]
Hi @myrne95,

OK, so it looks like my current implementation would load each z plane as a different channel. Maybe not the long term solution but my suit your current use case.

```
	/*
	example:
	A - 01(fld 1 wv Green - dsRed z 3).tif
	well = A - 01, site = 1, channel = 1
 	*/
	public static final String INCELL_EXAMPLE = "A - 01(fld 1 wv Green - dsRed z 3).tif";
	public static final String INCELL_WELL_SITE_CHANNEL = ".*(?<"+WELL+">[A-Z]{1} - [0-9]{2})\\(fld (?<"+SITE+">[0-9]{1}) (?<"+CHANNEL+">.*)\\).tif";
```

To test this, [please install MoBIE-beta](https://github.com/mobie/mobie-viewer-fiji/blob/develop/MOBIE-BETA.md#mobie-beta). Please note that I am discontinuing the PlateViewer plugin and am shifting all the functionality to the MoBIE plugin, so you won't need the PlateViewer plugin und update site anymore.

Then, hopefully the following steps should work....please first try exactly on the test data with the two wells that you shared with me, before trying other and larger data sets.

<img width="800" alt="image" src="https://github.com/embl-cba/plateviewer/assets/2157566/c9612421-93f9-40cd-99b7-78255feea300">

<img width="572" alt="image" src="https://github.com/embl-cba/plateviewer/assets/2157566/c39a29a5-3d82-422b-9999-2a8319e4ef71">

<img width="1423" alt="image" src="https://github.com/embl-cba/plateviewer/assets/2157566/d774d79a-8c71-45fc-8441-4097a0d1114e">

For help how to use MoBIE see:

- https://mobie.github.io/
- https://www.youtube.com/playlist?list=PLrkean19vFfHMBgLs2nQrO9TlWZu49f2z

**Comment by myrne95** [comment]
@tischi thank you! It seems to work with the MoBIE viewer :)

**Comment by tischi** [comment]
Awesome @myrne95 .

Then I will close this issue.

For further requests, please raise an issue here: https://github.com/mobie/mobie-viewer-fiji/issues

And it would help us to further develop this if you could _cite_ https://www.nature.com/articles/s41592-023-01776-4
